### PR TITLE
adapt to angular app running inside iframe

### PR DESCRIPTION
**Pull request by jinyangzhen**
A simple change to allow ng-stat snippet to monitor watches from angular app running inside iframe, for example Plunker and JSFiddle.

### CODE REVIEW

**Comment by kentcdodds** [comment]
Awesome! Could you give me a way that I can test this out myself? I'm not sure that I know exactly how to test this.

**Comment by jinyangzhen** [comment]
ng-stat

As attached screen shot
1. Launch a plunker case in Chrome
2. Open DevTool, and in console tab, switch to the iframe 'PlunkerPreviewTarget'
3. Add/Run ng-stat.js snippet in source tab
4. the monitoring chart will be displayed in result frame, indicates ng-stat is now set to monitoring the  plunker case instead of plunker itself :-)

**Comment by kentcdodds** [comment]
Ah! I didn't know you could do that! Cool! Give me some more time to look
at this and then I think this will definitely make it in! Thanks for
showing me that neat trick too!

-Kent C. Dodds

**Comment by kentcdodds** [comment]
Looks good to me! Thanks!

**Comment by kentcdodds** [comment]
Published as 2.2.0. Thanks!

**Comment by Jag-MW** [comment]
Hi, is there a way we can just use the api in the protractor tests to get the values of digest length?

**Pull request merged**
