### PR TITLE
Support Isolate Scope

### LINKED ISSUE #37: Support Isolate Scope
ng-stats blows up when there are only isolate scopes on the page. We can simply modify the query selector to include isolate scopes.

```js
document.querySelector('.ng-scope, .ng-isolate-scope');
```

### PR DESCRIPTION
**Pull request by daniellmb**
v2.3.2 closes #37

### CODE REVIEW

**Comment by kentcdodds** [comment]
Could you resubmit this PR without committing anything in the `dist` directory or updating the `version` in the `package.json` please? Adding yourself to `contributors` is fine with me.

**Comment by daniellmb** [comment]
lol sry I thought I was helping save you some work. I removed the dist and npm version number changes.

**Comment by kentcdodds** [comment]
No worries :-) I prefer to make PRs atomic so it's easier to trace back through the history to find out what happened. So I have a "release commit" which does nothing but update the version and the dist directory.

Unfortunately, it appears that changes to the dist directory are still in this PR. I also prefer each PR to have only a single commit in it if possible. Perhaps you could either resubmit the PR with only the changes that are necessary or update things with a single commit on your branch and do a `$ git push -f`

**Comment by daniellmb** [comment]
yeah let's just keep it simple... I'll resubmit...

**Pull request closed without merging**
