### PR TITLE
Remove moot `version` property from bower.json

### PR DESCRIPTION
**Pull request by kkirsche**
Per bower/bower.json-spec@a325da3

### CODE REVIEW

**Comment by SomeKittens** [comment]
From the comment you linked:

> Intended to be used in the future when Bower gets a real registry

Sounds like there's no problem with leaving this in for now.

**Comment by kkirsche** [comment]
That's fair. I don't expect that to ever happen to be honest, but feel free to keep it if you wish. As I understand it though from the discussions I've had the general recommendation is to use package managers like npm instead of bower due to significantly improved functionality and management.

Essentially, npm is what got the tools which things like version were for. While you may keep it the general understanding I've gotten is that the goal is to eventually kill bower to lower package manager fragmentation in the JS community. 

With that said, I could have misunderstood them during our discussions, but personally I wouldn't count on that ever getting used, especially not in the near future.

**Comment by kentcdodds** [comment]
I'm on the same page with you @kkirsche. Would love package management to become less fragmented in the JS community as well, and I prefer npm. But I think I'm going to keep the bower version going [on](https://github.com/kentcdodds/api-check/pull/22) [all](https://github.com/formly-js/angular-formly/pull/342) [my](https://github.com/formly-js/react-formly/pull/3) [repos](https://github.com/kentcdodds/ng-stats/pull/30) :laughing: 

Curious, how many repos did you make this PR to? I appreciate your enthusiasm :+1:

**Comment by kkirsche** [comment]
120+ yesterday. More today. Little things like this nag at the OCD part of me :smiley: I fully understand leaving it, I just want people aware that if they include it, it isn't doing anything and provide a quick option to remove it if they don't feel it's worth keeping when not used.

**Comment by kentcdodds** [comment]
Wow, that's awesome! :+1:

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by kkirsche** [comment]
Also their maintainer says they probably won't ever use it: http://stackoverflow.com/questions/24844901/bowers-bower-json-file-version-property

**Comment by kentcdodds** [comment]
Looks like I've pushed a new version since you opened this. I'll remove it next chance I get :-)

**Pull request closed without merging**
