### PR TITLE
Fix issue #59

### PR DESCRIPTION
**Pull request by amirgon**

### CODE REVIEW

**Comment by kentcdodds** [comment]
Ignore snapCI. Does this work for you then? I don't really use this to anymore

**Comment by amirgon** [comment]
It works for me.
I did not update the .js.min/map files though, since I edited the source file online on GitHub.

**Comment by kentcdodds** [comment]
Understood. I'll have to pull this down and rebuild/release tomorrow. Thanks!

**Comment by kentcdodds** [comment]
Released.

**Comment by amirgon** [comment]
9655b4c199e7913a210f1316eadb6ea0d08ddc43 reverted this?

**Comment by kentcdodds** [comment]
Oh dear... Looks like we just got nailed by [this](https://kcd.im/generated):

screen shot 2016-07-14 at 9 46 03 am

I'll fix it up.

**Comment by amirgon** [comment]
Right. Sorry about that.

**Comment by kentcdodds** [comment]
Alrighty, we should be good now.

**Comment by kentcdodds** [comment]
Note: I realized that we don't actually need to get `setTimeout` and `clearTimeout` from `window.self`. It doesn't make a difference :-)

**Pull request merged**
